name: olivine_mosquitto

services:
  broker:
    image: eclipse-mosquitto
    ports:
      - 1883:1883
      - 8081:8081
    volumes:
      - ./mosquitto.conf:/mosquitto/config/mosquitto.conf
      - data:/mosquitto/data
      - log:/mosquitto/log

volumes:
  data:
  log:
