name: olivine_mosquitto

services:
  broker:
    image: eclipse-mosquitto
    ports:
      - 1883:1883
      - 8081:8081
    volumes:
      - ./mosquitto.conf:/mosquitto/config/mosquitto.conf
      - data:/mosquitto/data
      - log:/mosquitto/log

  db:
    image: influxdb:latest
    ports:
      - 8086:8086
    volumes:
      - db_data:/var/lib/influxdb2
      - db_config:/etc/influxdb2
    environment:
      DOCKER_INFLUXDB_INIT_USERNAME: root
      DOCKER_INFLUXDB_INIT_PASSWORD: norco
      DOCKER_INFLUXDB_INIT_ORG: norco-college-rocketry
      DOCKER_INFLUXDB_INIT_BUCKET: olivine

volumes:
  data:
  log:
  db_data:
  db_config:
